src/br/com/caelum/financas/mb/CacheBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import br.com.caelum.financas.modelo.Conta;

@Named
@RequestScoped
public class CacheBean {
	
	@Inject
	private EntityManager manager;
	
	private Integer id;
	private Conta conta;
	
	public void pesquisar() {
		this.conta = this.manager.find(Conta.class, id);
		this.conta = this.manager.find(Conta.class, id);
		System.out.println("Testando cache de primeiro nivel");
	}

	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Conta getConta() {
		return conta;
	}
	
}

src/br/com/caelum/financas/mb/CacheInvalidaBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.Cache;

import br.com.caelum.financas.modelo.Conta;

@Named
@RequestScoped
public class CacheInvalidaBean {
	
	@Inject
	private Cache cache;
	
	private Integer id;
	private Conta conta;
	

	public void invalidar() {
		System.out.println("Invalidando o cache programaticamente");
		cache.evict(Conta.class, id);
	}

	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Conta getConta() {
		return conta;
	}
}

src/br/com/caelum/financas/mb/CicloDeVidaBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.service.Agendador;

@Named
@RequestScoped
public class CicloDeVidaBean {
	
	@Inject
	private Agendador agendador;
	
	public void executeAgendador() {
		agendador.executa();
	
	}
}

src/br/com/caelum/financas/mb/ContasBean.java
package br.com.caelum.financas.mb;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.ContaDao;
import br.com.caelum.financas.dao.GerenteDao;
import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.GerenteConta;

@Named
@ViewScoped
public class ContasBean implements Serializable {
    
    private static final long serialVersionUID = 1L;

    @Inject
    private ContaDao contaDao;
    @Inject
    private MovimentacaoDao movimentacaoDao;
    @Inject
    private GerenteDao gerenteDao;
	private Conta conta = new Conta();
	private List<Conta> contas;
	private Integer gerenteId;

	public GerenteDao getGerenteDao() {
		return gerenteDao;
	}

	public void setGerenteDao(GerenteDao gerenteDao) {
		this.gerenteDao = gerenteDao;
	}

	public Integer getGerenteId() {
		return gerenteId;
	}

	public void setGerenteId(Integer gerenteId) {
		this.gerenteId = gerenteId;
	}
	
	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public void grava() {
//		if(gerenteId != null) {
//			Gerente gerenteRelacionamento = gerenteDao.busca(gerenteId);
//			this.conta.setGerente(gerenteRelacionamento);
//		}
		if(gerenteId != null) {
			GerenteConta gerenteRelacionado = gerenteDao.busca(gerenteId);
			gerenteRelacionado.setNumeroDaConta(this.conta.getNumero());
			this.conta.setGerente(gerenteRelacionado);
		}
		if(this.conta.getId() == null) {
			contaDao.adiciona(conta);
		}else {
			contaDao.altera(conta);
		}
		
		this.contas = contaDao.lista();
		System.out.println("Gravando a conta do títular" + conta.getTitular());

		limpaFormularioDoJSF();
	}

	public List<Conta> getContas() {
		if(this.contas == null) {
			this.contas = contaDao.lista();
		}
		System.out.println("Listando as contas");

		return this.contas;
	}

	public void remove() {
		contaDao.busca(this.conta.getId());
		
		contaDao.remove(this.conta);
		this.contas = contaDao.lista();
		
		System.out.println("Removendo a conta");

		limpaFormularioDoJSF();
	}

	/**
	 * Esse metodo apenas limpa o formulario da forma com que o JSF espera.
	 * Invoque-o no momento em que precisar do formulario vazio.
	 */
	private void limpaFormularioDoJSF() {
		this.conta = new Conta();
		gerenteId = null;
	}
	
}

src/br/com/caelum/financas/mb/CriteriaBean.java
package br.com.caelum.financas.mb;

import java.math.BigDecimal;
import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Movimentacao;

@Named
@RequestScoped
public class CriteriaBean {
	
	@Inject
	private MovimentacaoDao movimentacaoDao;
	private List<Movimentacao> movimentacoes;
	private BigDecimal soma;
	
	private String titular;
	

	public void listarTodasAsMovimentacoes() {
		this.movimentacoes = this.movimentacaoDao.listaTodasComCriteria();
	}

	public void somaMovimentacoesDoTitular() {
		this.soma = movimentacaoDao.somaMovimentacoesDoTitular(this.titular);
	}
	
	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}
	
	public BigDecimal getSoma() {
		return soma;
	}
	
	public String getTitular() {
		return titular;
	}
	
	public void setTitular(String titular) {
		this.titular = titular;
	}
}

src/br/com/caelum/financas/mb/EstatisticasBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.hibernate.Session;
import org.hibernate.stat.Statistics;


@Named
@ApplicationScoped
public class EstatisticasBean {

		@Inject
		private EntityManager manager;
		
		private Statistics estatisticas;
	
		public Statistics getEstatisticas() {
			return estatisticas;
		}

		public void setEstatisticas(Statistics estatisticas) {
			this.estatisticas = estatisticas;
		}

		public void gera() {
			System.out.println("Gerando estatísticas");
			Session session = this.manager.unwrap(Session.class);
			this.estatisticas = session.getSessionFactory().getStatistics();
		}
}

src/br/com/caelum/financas/mb/GerentesBean.java
package br.com.caelum.financas.mb;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.GerenteDao;
import br.com.caelum.financas.modelo.Gerente;
import br.com.caelum.financas.modelo.GerenteConta;

@Named
@ViewScoped
public class GerentesBean implements Serializable{
	
	private static final long serialVersionUID = 1L;

	@Inject
	private GerenteDao dao;

	private List<Gerente> gerentes;
	
	private Gerente gerente = new GerenteConta();

	
	//Getters and setters
	public GerenteDao getDao() {
		return dao;
	}

	public void setDao(GerenteDao dao) {
		this.dao = dao;
	}

	public List<Gerente> getGerentes() {
		if(this.gerentes == null) {
			this.gerentes = dao.lista();
		}
		return gerentes;
	}

	public void setGerentes(List<Gerente> gerentes) {
		this.gerentes = gerentes;
	}

	public Gerente getGerente() {
		return gerente;
	}

	public void setGerente(Gerente gerente) {
		this.gerente = gerente;
	}
	
	public void grava() {
		if(this.gerente.getId() == null) {
			dao.adiciona(gerente);
		}else {
			dao.altera(gerente);
		}
		
		this.gerentes = dao.lista();
		System.out.println("Gravando o gerente: " + gerente.getNome());

		limpaFormularioDoJSF();
	}

	public void remove() {
		dao.busca(this.gerente.getId());
		
		dao.remove(this.gerente);
		this.gerentes = dao.lista();
		
		System.out.println("Removendo o gerente");

		limpaFormularioDoJSF();
	}
	
	private void limpaFormularioDoJSF() {
		this.gerente = new GerenteConta();

	}

}

src/br/com/caelum/financas/mb/MesesComMovimentacaoBean.java
package br.com.caelum.financas.mb;


import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.TipoMovimentacao;
import br.com.caelum.financas.modelo.ValorPorMesEAno;

@Named
@RequestScoped
public class MesesComMovimentacaoBean {

	@Inject
	private MovimentacaoDao dao;
	
	
	private Conta conta = new Conta();
	private List<ValorPorMesEAno> valoresPorMesEAno;

	private TipoMovimentacao tipoMovimentacao;
	
	public void lista() {
		System.out.println("Listando as contas pelos valores movimentados no mes");
		valoresPorMesEAno = dao.listaMesesComMovimentacoes(conta, tipoMovimentacao);
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

	public Conta getConta() {
		return conta;
	}

	public List<ValorPorMesEAno> getValoresPorMesEAno() {
		return valoresPorMesEAno;
	}
	
	

}

src/br/com/caelum/financas/mb/MovimentacoesBean.java
package br.com.caelum.financas.mb;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.CategoriaDao;
import br.com.caelum.financas.dao.ContaDao;
import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Categoria;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.Movimentacao;
import br.com.caelum.financas.modelo.TipoMovimentacao;

@Named
@ViewScoped
public class MovimentacoesBean implements Serializable {

	@Inject
	private MovimentacaoDao movimentacaoDao;
	@Inject
	private ContaDao contaDao;
	private static final long serialVersionUID = 1L;
	@Inject
	private CategoriaDao categoriaDao;
	
	private List<Movimentacao> movimentacoes;
	private Movimentacao movimentacao = new Movimentacao();
	private Integer contaId;
	private Integer categoriaId;
	private List<Categoria> categorias;
	
	
	public void grava() {
		Conta contaRelacionada = contaDao.busca(contaId);
		movimentacao.setConta(contaRelacionada);
		movimentacaoDao.adiciona(movimentacao);
		
		this.movimentacoes = movimentacaoDao.listaComCategorias();
		System.out.println("Fazendo a gravacao da movimentacao");
		
		limpaFormularioDoJSF();
	}
	

	public void remove() {
		movimentacaoDao.remove(this.movimentacao);
		this.movimentacoes = movimentacaoDao.listaComCategorias();
		System.out.println("Removendo a movimentacao");

		
		limpaFormularioDoJSF();
	}

	public List<Movimentacao> getMovimentacoes() {
		if(this.movimentacoes == null) {
			this.movimentacoes = movimentacaoDao.lista();
		}
		
		return movimentacoes;
	}
	
	public Movimentacao getMovimentacao() {
		if(movimentacao.getData()==null) {
			movimentacao.setData(LocalDateTime.now());
		}
		
		return movimentacao;
	}

	public void adicionaCategoria() {
		if(this.categoriaId != null && this.categoriaId > 0) {
			Categoria categoria = categoriaDao.procura(this.categoriaId);
			this.movimentacao.getCategorias().add(categoria);
		}
	}
	
	public List<Categoria> getCategorias() {
		if(this.categorias == null) {
			System.out.println("Listando as categorias");
			this.categorias = this.categoriaDao.lista();
		}
		return this.categorias;
	}


	public void setMovimentacao(Movimentacao movimentacao) {
		this.movimentacao = movimentacao;
	}

	public Integer getContaId() {
		return contaId;
	}

	public void setContaId(Integer contaId) {
		this.contaId = contaId;
	}
	

	public Integer getCategoriaId() {
		return categoriaId;
	}

	public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	/**
	 * Esse metodo apenas limpa o formulario da forma com que o JSF espera.
	 * Invoque-o no momento manager que precisar do formulario vazio.
	 */
	private void limpaFormularioDoJSF() {
		this.movimentacao = new Movimentacao();
	}

	public TipoMovimentacao[] getTiposDeMovimentacao() {
		return TipoMovimentacao.values();
	}
}

src/br/com/caelum/financas/mb/MovimentacoesDaContaBean.java
package br.com.caelum.financas.mb;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.Movimentacao;

@Named
@RequestScoped
public class MovimentacoesDaContaBean {

	@Inject
	private MovimentacaoDao dao;
	
	private List<Movimentacao> movimentacoes;
	private Conta conta = new Conta();
	
	public void lista() {
		movimentacoes = dao.listaTodasMovimentacoes(conta);
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}
}

src/br/com/caelum/financas/mb/MovimentacoesPorTitularBean.java
package br.com.caelum.financas.mb;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Movimentacao;

@Named
@RequestScoped
public class MovimentacoesPorTitularBean {

	@Inject
	private MovimentacaoDao dao;
	
	
	private List<Movimentacao> movimentacoes;
	private String titular;
	
	public void lista() {
		System.out.println("Buscando as movimentacoes pelo titular da conta " + this.titular);
		movimentacoes = dao.buscaTodasMovimentacoesDaConta(titular);
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

	public String getTitular() {
		return titular;
	}

	public void setTitular(String titular) {
		this.titular = titular;
	}

}

src/br/com/caelum/financas/mb/MovimentacoesPorValorETipoBean.java
package br.com.caelum.financas.mb;

import java.math.BigDecimal;
import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Movimentacao;
import br.com.caelum.financas.modelo.TipoMovimentacao;

@Named
@RequestScoped
public class MovimentacoesPorValorETipoBean {
	
	@Inject
	private MovimentacaoDao dao;
	
	private List<Movimentacao> movimentacoes;
	private BigDecimal valor;
	private TipoMovimentacao tipoMovimentacao;


	public void lista() {
		System.out.println("Buscando movimentacoes por valor e tipo");
		movimentacoes = dao.listaPorValorETipo(valor, tipoMovimentacao);
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

}

src/br/com/caelum/financas/mb/OperacaoEmLoteBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.ContaDao;

@Named
@RequestScoped
public class OperacaoEmLoteBean {
	
	@Inject
	private ContaDao dao;
	private String antigoNomeBanco;
	private String novoNomeBanco;
	private int contasAlteradas;
	
	public void atualizar() {
		this.contasAlteradas = dao.trocaNomeDoBancoEmLote(antigoNomeBanco, novoNomeBanco);
		
		
		System.out.println("Quantidade de contas alteradas: " + contasAlteradas);
		this.limpaFormularioDoJSF();
	}

	public String getAntigoNomeBanco() {
		return antigoNomeBanco;
	}

	public void setAntigoNomeBanco(String antigoNomeBanco) {
		this.antigoNomeBanco = antigoNomeBanco;
	}

	public String getNovoNomeBanco() {
		return novoNomeBanco;
	}

	public void setNovoNomeBanco(String novoNomeBanco) {
		this.novoNomeBanco = novoNomeBanco;
	}

	public int getContasAlteradas() {
		return contasAlteradas;
	}

	private void limpaFormularioDoJSF() {
		this.antigoNomeBanco = "";
		this.novoNomeBanco = "";
	}	
	
}

src/br/com/caelum/financas/mb/PesquisaMovimentacoesBean.java
package br.com.caelum.financas.mb;

import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.ContaDao;
import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.Movimentacao;
import br.com.caelum.financas.modelo.TipoMovimentacao;

@Named
@RequestScoped
public class PesquisaMovimentacoesBean {

	@Inject
	private MovimentacaoDao movimentacaoDao;
	@Inject
	private ContaDao contaDao;
	private Conta conta = new Conta();
	private Integer mes;
	private TipoMovimentacao tipoMovimentacao;
	private List<Movimentacao> movimentacoes;

	
	public void pesquisa() {
		System.out.println("Pesquisando pelos filtros solicitados");
		movimentacoes = movimentacaoDao.pesquisa(getConta(), tipoMovimentacao, getMes());
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

	public Conta getConta() {
		if(conta.getId()!=null) {
			conta = contaDao.busca(conta.getId());
		}
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public Integer getMes() {	
		if(mes!=null && mes==0) {
			mes=null;
		}
		return mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

}

WebContent/mesesComMovimentacao.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			  <html xmlns="http://www.w3.org/1999/xhtml"
					xmlns:ui="http://java.sun.com/jsf/facelets"
					xmlns:f="http://java.sun.com/jsf/core"
					xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/_template.xhtml">
   		<ui:define name="cabecalho">
		   <h:outputText value="Movimentações por mês" />
    	</ui:define>
		   
   		<ui:define name="corpo">
			 <h:form>
			  	<h:panelGrid columns="2">
			  		<h:outputText value="Conta"/>
			      	<h:selectOneMenu value="#{mesesComMovimentacaoBean.conta.id}">
			      		<f:selectItem itemLabel="Escolha a conta" itemValue="" noSelectionOption="true"/>
			      		<f:selectItems value="#{contasBean.contas}" var="conta" itemLabel="#{conta.titular} - #{conta.banco}" itemValue="#{conta.id}" />
			      	</h:selectOneMenu>
			      	
			      	<h:outputText value="Tipo" />
				   	<h:selectOneMenu value="#{mesesComMovimentacaoBean.tipoMovimentacao}">
				   		<f:selectItem itemLabel="Escolha o tipo" itemValue="" noSelectionOption="true"/>
				   		<f:selectItems value="#{movimentacoesBean.tiposDeMovimentacao}" />
				   	</h:selectOneMenu>
			     	
			  		<h:commandButton value="Pesquisar" action="#{mesesComMovimentacaoBean.lista}"/>
				</h:panelGrid>
			</h:form>
    
	        <h2><h:outputText value="Todas as Movimentações" /></h2>
	        <hr />
	        <h:dataTable value="#{mesesComMovimentacaoBean.valoresPorMesEAno}" var="valorPorMesEAno">
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Mês" />
	        		</f:facet>
	        		#{valorPorMesEAno.mes}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Ano" />
	        		</f:facet>
	        		#{valorPorMesEAno.ano}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Valor" />
	        		</f:facet>
	        		#{valorPorMesEAno.valor}
	        	</h:column>
	        </h:dataTable>
    		</ui:define>
	</ui:composition>
</html>

WebContent/movimentacoes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			  <html xmlns="http://www.w3.org/1999/xhtml"
					xmlns:ui="http://java.sun.com/jsf/facelets"
					xmlns:f="http://java.sun.com/jsf/core"
					xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/_template.xhtml">
   		<ui:define name="cabecalho">
			<h:outputText value="Cadastro de Movimentações" />
    	</ui:define>
		   
   		<ui:define name="corpo">
 
		   <h:form>
		   	<f:validateBean disabled="true">
	        	<h:messages />
		   		<h:panelGrid columns="2">
		    	
		    	<h:outputText value="Conta"/>
	        	<h:selectOneMenu value="#{movimentacoesBean.contaId}">
	        		<f:selectItem itemLabel="Escolha a conta" itemValue="" noSelectionOption="true"/>
	        		<f:selectItems value="#{contasBean.contas}" var="conta" itemLabel="#{conta.titular} - #{conta.banco}" itemValue="#{conta.id}" />
	        	</h:selectOneMenu>
	        	
	        	<h:outputText value="Descrição" />
	        	<h:inputTextarea value="#{movimentacoesBean.movimentacao.descricao}" />
	        	
	        	<h:outputText value="Valor" />
		    	<h:inputText value="#{movimentacoesBean.movimentacao.valor}" />
		    	
		    	<h:outputText value="Tipo" />
		    	<h:selectOneMenu value="#{movimentacoesBean.movimentacao.tipoMovimentacao}">
		    		<f:selectItem itemLabel="Escolha o tipo" itemValue="" noSelectionOption="true"/>
		    		<f:selectItems value="#{movimentacoesBean.tiposDeMovimentacao}" />
		    	</h:selectOneMenu>		   		    
		    	
		    	<h:outputText value="Data" />
		    	<h:inputText value="#{movimentacoesBean.movimentacao.data}">
		    		<f:converter converterId="localDateTimeConverter" />
		    	</h:inputText>
		    	
		        <h:outputText value="Categorias" rendered="true"/>
		    	<h:panelGroup rendered="true">
		        	<h:selectOneMenu value="#{movimentacoesBean.categoriaId}" id="selectCategoria">
			    		<f:selectItem itemLabel="Escolha a Categoria" itemValue="" noSelectionOption="true"/>
			    		<f:selectItems value="#{movimentacoesBean.categorias}" var="categoria" itemValue="#{categoria.id}" itemLabel="#{categoria.nome}"/>
			    	</h:selectOneMenu>
				    <h:commandButton value="+" action="#{movimentacoesBean.adicionaCategoria}" >
				    	<f:ajax execute="selectCategoria" render="tblCategoria"/>
				    </h:commandButton>
			    	<h:dataTable value="#{movimentacoesBean.movimentacao.categorias}" var="categoria" id="tblCategoria" >
			    		<h:column>
			    			<h:outputText value="#{categoria.nome}" />
			    		</h:column>
			    	</h:dataTable>
			    </h:panelGroup>
	
				<br />
				
			    <h:commandButton value="Gravar" action="#{movimentacoesBean.grava}"/>
		    	</h:panelGrid>
		    </f:validateBean>
		   </h:form>
    
	        <h2><h:outputText value="Todas as Movimentações" /></h2>
	        <hr />
	       <h:form>
	        <h:dataTable value="#{movimentacoesBean.movimentacoes}" var="movimentacao">
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="ID" />
	        		</f:facet>
	        		#{movimentacao.id}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Conta" />
	        		</f:facet>
	        		#{movimentacao.conta.titular} - #{movimentacao.conta.banco}
	        	</h:column>
	        	<h:column>
					<f:facet name="header">
						<h:outputText value="Valor" />
					</f:facet>
					<h:outputText value="#{movimentacao.valor}" >
						<f:convertNumber pattern="R$ #0.00"/>
					</h:outputText>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Data" />
					</f:facet>
					<h:outputText value="#{movimentacao.data}" >
						<f:converter converterId="localDateTimeConverter"/>
					</h:outputText>
				</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Descrição" />
	        		</f:facet>
	        		#{movimentacao.descricao}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Tipo" />
	        			
	        		</f:facet>
	        		#{movimentacao.tipoMovimentacao}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Categorias" />
	        		</f:facet>        		
	        		#{movimentacao.categorias}
	        	</h:column>        	
	        	<h:column>
	        		<f:facet name="header"><h:outputText value="Ações"/></f:facet>
	        			<h:commandLink value="Remover" action="#{movimentacoesBean.remove}">
							<f:setPropertyActionListener value="#{movimentacao}" target="#{movimentacoesBean.movimentacao}"/>
	        			</h:commandLink>
	        	</h:column>
	        </h:dataTable>  
	       </h:form>
		</ui:define>
	</ui:composition>

</html>